# fly.toml app configuration file generated for rce on 2024-08-17T18:10:31+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rce'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
